### ISSUE TITLE
Twitch Notifications

### ISSUE THREAD

**Issue by jateute** [SCNetwork/CustomDCBot#14]
If nobody of the team is working on a module that sends a message if a Twitch-Streamer goes live, I'll start working on it today at 17 o'clock (German time) or tomorrow.

**Comment by SCDerox** [comment]
Hi,
sure, go ahead!
If you have any questions feel free to contact me on Discord: SCDerox#465!

**Comment by SCDerox** [comment]
Any updates on this?

**Comment by jot737** [comment]
Yes, the first version is ready, but it doesn't work. I'll Code it again, that it's cleaner and find then the bugs.

**Comment by SCDerox** [comment]
Do you have any updates on this? I just want to make sure this is actively worked on ^^

**Comment by jateute** [comment]
Yes, It's ready, but there is an Error when I start it. I think it's an Error in my File/ Folder Names or in my module.json File. I'll work on it next week (12 July), because then i'll be home again.

**Comment by SCDerox** [comment]
Sure, feel free to message me, if you need any help debugging it ^^

**Comment by SCDerox** [comment]
Well, it's been over 19 days again, any new updates? If not, I would implement this feature myself... 
It would be great, if we had a working version by next week.

**Comment by jateute** [comment]
I'm sorry, but on Friday I was unable to upload my work and fix an error. At the moment I'm not at home (again), so I can't access my work. I'll be back at the 9th of August. If this is too late for you you could take my work as base and finish the module
