### ISSUE TITLE
welcomer don't work

### ISSUE THREAD

**Issue by GregorKeks** [SCNetwork/CustomDCBot#18]
Hello,
I have a problem with the module Welcomer.
I have just set up the bot, nothing changed. I have only the module welcomer active and all IDs set. The bot has full administration rights. But as soon as someone comes on the DC, no message appears or only the standard message. There is also no error message in the console or in the log.

Have I done something wrong?

Mfg.
~ Gregor

**Comment by SCDerox** [comment]
Please enable the GUILD_MEMBERS Intent in your discord developer panel and try again.

**Comment by GregorKeks** [comment]
Sorry but where do you enable this?

**Comment by SCDerox** [comment]
In your discord developer panel under under bot. Feel free to Google it, if you can't find it

**Comment by GregorKeks** [comment]
Thanks for your quick help. :-D
