### ISSUE TITLE
setup reaction-role

### ISSUE THREAD

**Issue by GregorKeks** [SCNetwork/CustomDCBot#19]
Hello,
Sorry to bother you again, but I'm too stupid to set up reaction-role right now. ^^

**Comment by SCDerox** [comment]
Hi,
reaction-roles uses "configElements" which means that you need to create an array of elements containing the keys specified in the config generation file. 
If you want an easy to use webpanel and free 24/7 hosting for your bot with even more features, feel free to check out [SCNX](https://scnx.xyz) (currently only German).

**Comment by SCDerox** [comment]
If you have any further questions, please create a discussion in the discussion tab, as issues are reserved for bugs and suggestions.
