### ISSUE TITLE
Auto Rename Module

### ISSUE THREAD

**Issue by lithium-lx** [SCNetwork/CustomDCBot#23]
This is a very small, niche module, but maybe it's useful for others too:
The module renames the bot on startup to a name specified in the (global) config file.

This module is useful for me because I launch my "dev" and "stable" bot from the same terminal and working directory with the only difference being the config. I want to make it clear for users that we are currently running a "dev" version, not the usual one.

Example:
My Bot →My Bot (debug mode)

**Comment by lithium-lx** [comment]
The core functionality is now implemented, I just need to handle potential errors now

**Comment by lithium-lx** [comment]
Is that module interesting for you? I already have it working.

**Comment by SCDerox** [comment]
So is this only changing the nick name? I don't really see why that would be useful in a production environment like we run for our customers

**Comment by lithium-lx** [comment]
Yeah, it does only change that. I think you are right, this probably isn't useful for them (closing this issue).

**Comment by SCDerox** [comment]
It could be useful if we allow users to use variables like %guildName% or %memberCount% or something similar or allow them to change the nickname automatically in a specified interval. 
Sorry for the late response by the way, I am currently on vacation. 
If you need inspiration for new modules or just want to chat about possible new features, feel free to DM me on discord: SCDerox#4645 ^^
