### ISSUE TITLE
Sending messages on Server Boosts 

### ISSUE THREAD

**Issue by HerobrineProMC** [SCNetwork/CustomDCBot#30]
If nobody is working on this I will create a module for [CustomBot-Feature-Request 133](https://features.sc-network.net/board/custombot/133) from the Feature Board.

**Comment by SCDerox** [comment]
Hi, thanks for your interest in our project. Please use [the dev branch](https://github.com/SCNetwork/CustomDCBot/tree/dev) when developing and later pull-requesting.
It would be great if you could add this feature to another module as it's not worth creating a new module for it - maybe `welcomer`?

**Comment by HerobrineProMC** [comment]
It's ok. Then I will add the feature to the Welcomer-Module.

**Comment by SCDerox** [comment]
I will have to rework the welcomer module in V2 and will implement this feature as it's not really a big deal and you haven't updated this issue for more than 12 days.
