### ISSUE TITLE
Brauche Hilfe bei [Moderation] Auto Mod

### ISSUE THREAD

**Issue by amorking1996** [SCNetwork/CustomDCBot#31]
Hallo ich benötige hilfe beim einrichten von auto mod war muss ich da eintragen aktuell siehts so aus   "automod": {}

lg

**Comment by SCDerox** [comment]
Hi, If you have any questions to open source software, please use the [discussions}(https://github.com/SCNetwork/CustomDCBot/discussions)-tab. Please also respect the language of this repository which is English.
